modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="audioplayer"
version="${file.jarVersion}"
displayName="AudioPlayer"
logoFile="examplemod.png"
credits=""
authors="Max Henkel"
description='''Audio Player'''

[[dependencies.audioplayer]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.audioplayer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.audioplayer]]
    modId="voicechat"
    mandatory=true
    versionRange="[1.19.2-2.3.18,)"
    ordering="NONE"
    side="BOTH"